// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvbkbtolrlfhnfruklqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2YmtidG9scmxmaG5mcnVrbHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzI4NTIsImV4cCI6MjA2NjI0ODg1Mn0.7sZJtWjn9jiRqhj9shcwqqbMah2VerFophG5XPYyL5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);